### ISSUE TITLE
[USER] GLADHOST

### ISSUE THREAD

**Issue by henri9813** [gogrlx/grlx#115]
**What is your company name?**
GLADHOST

**What is the focus of your company?**
Web hosting

**Please provide the URL to your company homepage:**
https://gladhost.cloud

**Please link us to a hosted copy of your company logo to include in the README:**
![logo](https://github.com/user-attachments/assets/5601bfa6-d966-4b25-9c04-b5ab176fbfd1)

**Additional context**

**Comment by taigrr** [comment]
your logo is transparent and the Gladhost text is invisible on github's dark mode. If you prefer a white background, please upload a png to this issue and reopen it. otherwise, I'll assume the logo you provided is what you want to use.
![image](https://github.com/user-attachments/assets/cc872a7a-68bf-423e-a146-6afb3a61335d)
